site_name: LearnOpenGL Korean

site_description: https://learnopengl.com의 한국어 번역입니다.

site_url: https://learnoglko.github.io/

theme:
  name: material

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - footnotes
  - abbr
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - css/style.css

nav:
  - 소개: index.md
  - 시작하기:
    - OpenGL: 시작하기/OpenGL.md
    - 최초의 창: 시작하기/최초의 창.md
    - 리눅스에서의 최초의 창: 시작하기/최초의 창-리눅스.md
    - 안녕 창: 시작하기/안녕 창.md
    - 안녕 삼각형: 시작하기/안녕 삼각형.md
    - 셰이더: 시작하기/셰이더.md
    - 텍스쳐: 시작하기/텍스쳐.md
    - 변형: 시작하기/변형.md
    - 좌표 공간: 시작하기/좌표 공간.md
    - 카메라: 시작하기/카메라.md
    - 끝: 시작하기/끝.md
  - 조명:
    - 색깔: 조명/색깔.md
    - 기본적인 조명 효과: 조명/기본적인 조명 효과.md
    - 머티리얼: 조명/머티리얼.md
    - 조명 맵: 조명/조명 맵.md
    - 다양한 광원 모델: 조명/다양한 광원 모델.md
    - 여러 개의 조명: 조명/여러 개의 조명.md
    - 끝: 조명/끝.md
  - 모델 로딩:
    - Assimp: 모델 로딩/Assimp.md
    - 메시: 모델 로딩/메시.md
    - 모델: 모델 로딩/모델.md
  - 고급 OpenGL:
    - 깊이 테스트: 고급 OpenGL/깊이 테스트.md
    - 스텐실 테스트: 고급 OpenGL/스텐실 테스트.md
    - 블렌딩: 고급 OpenGL/블렌딩.md
    - 페이스 컬링: 고급 OpenGL/페이스 컬링.md